FROM python:3.8-slim

# updating ubuntu packages
RUN apt-get -y update && apt-get -y upgrade

# install git for installing cgrdb from github
RUN apt-get install git -y
# Jupyter installation
RUN pip3 install jupyter

# 
RUN mkdir db_config
COPY ./configfiles/config.json /db_config

# script for delaying setup until DB is ready (until its port is availaible)
COPY ./bash_scripts/wait-for-it.sh /
RUN chmod 777 wait-for-it.sh
RUN chmod +x wait-for-it.sh


COPY . . 